

download:
	wget https://raw.githubusercontent.com/polyrhythm-project/accentuation-analysis/master/stacked_layered_accents_grouped_butterfly.JSON -O stacked_layered_accents_grouped_butterfly.json


data-test: test-data
td: test-data
dt: test-data
test-data:
	wget https://raw.githubusercontent.com/polyrhythm-project/accentuation-analysis/master/161S.tsv -O 161S.tsv


